### PR TITLE
add gen_image, img2lmdb

### PR DESCRIPTION
**Pull request by ZhangXinNan**
* add gen_image.py  generate image for training
* create_dataset.py is from [crnn](https://github.com/bgshih/crnn)
* create_dataset_main.py  image 2 lmdb

### CODE REVIEW

**Comment by meijieru** [comment]
Training examples mostly come from standard datasets, and there are various fantastic text image synthesize engine. So I don't think we should have a image generator here.

Also, images -> lmdb comes from origin repository, there is no need for a duplicate.

Thanks for your PR.

**Comment by ZhangXinNan** [comment]
I hope it keeps its independent and make it easy for others to get started.

**Comment by jxlijunhao** [comment]
@ZhangXinNan while have you test the generated chinese character could be save to lmdb, currently some of us have faced the "TypeError: Won't implicitly convert Unicode to bytes; use .encode()" errors.

**Comment by daoqinzi** [comment]
@jxlijunhao 我也遇到这个问题了，发现是python版本的原因，改成python2.7就好了

**Comment by gittigxuy** [comment]
@daoqinzi 可以把自己的数据集，含有多个中文的区域的图片制作成lmdb格式的文件吗？如何做呢？可否详细说明一下

**Comment by daoqinzi** [comment]
@gittigxuy  可以先按照 @ZhangXinNan 的 gen_image  create_dataset_main 跟一边代码就清楚些了

**Comment by Aurora11111** [comment]
@daoqinzi   Is it that all your code such as image,image_to_lmdb,crnn_main were run in  python2.7?

**Pull request closed without merging**
